name: test guthub action

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
  pull_request:

env:
  DOCKER_IMAGE_NAME: check1
  DOCKER_REGISTRY_URL: myregistry.domain.com

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: flexxoble/${{ env.DOCKER_IMAGE_NAME }}:latest